# Generated by Django 5.0.2 on 2024-02-26 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_extraction_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extracteddata',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
