# Generated by Django 5.0.2 on 2024-02-26 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_extraction_app', '0002_alter_extracteddata_invoice_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extracteddata',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
